# Generated by Django 5.2 on 2025-04-13 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Art', 'Art'), ('Food', 'Food'), ('Business', 'Business'), ('Hobbies', 'Hobbies'), ('Nightlife', 'Nightlife'), ('Holidays', 'Holidays'), ('Dates', 'Dates')], max_length=100),
        ),
    ]
