# Generated by Django 5.2 on 2025-04-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_tickets',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
