# Generated by Django 5.2 on 2025-04-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_ticket_total_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
