# Generated by Django 5.2 on 2025-04-11 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('event_manager', 'Event Manager')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('hobbies', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('social_media', models.TextField(blank=True)),
                ('notifications', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
