# Generated by Django 5.2 on 2025-04-11 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(default='defaultuser', max_length=150)),
                ('email', models.EmailField(default='noemail@example.com', max_length=254)),
                ('phone', models.CharField(default='N/A', max_length=15)),
                ('password', models.CharField(default='defaultpass123', max_length=128)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='other', max_length=10)),
                ('hobbies', models.TextField(default='None')),
                ('address', models.TextField(default='Unknown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
