# Generated by Django 5.2 on 2025-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmanager',
            name='username',
        ),
        migrations.AlterField(
            model_name='eventmanager',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='eventmanager',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='eventmanager',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='eventmanager',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
